name: FeatureBranch-PullRequest-WorkFlow
on:
  push:
    branches: [ develop ]

jobs:
  Docker-Login:
    runs-on: ubuntu-latest
    steps:
    - name: chekout repository
      uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}} 
    - name: image build
      run: docker image build -t ${{secrets.DOCKERHUB_USERNAME}}/nest-js-demo:latest .
    - name: image list
      run: docker images
    - name: docker push ${{secrets.DOCKERHUB_USERNAME}}/nest-js-demo:latest