  
name: FeatureBranch-PullRequest-WorkFlow

on:

  pull_request:
    branches: [ develop ]

jobs:
  Lint-Rules:
    runs-on: ubuntu-latest
    steps:
    - name: chekout repository
      uses: actions/checkout@v2
    - name: yarn install
      run: yarn install
    - name: Lint Kontrol Ediliyor
      run: yarn lint
  Format-Check:
    runs-on: ubuntu-latest
    steps:
    - name: chekout repository
      uses: actions/checkout@v2
    - name: yarn install
      run: yarn install
    - name: Format Checking Steps Are Running
      run: yarn format:check
  Unit-Test:
    #needs: [Lint-Rules, Format-Check]
    runs-on: ubuntu-latest
    steps:
    - name: chekout repository
      uses: actions/checkout@v2
    - name: yarn install
      run: yarn install
    - name: Unit Test Being Done
      run: yarn test:cov
  E2E-Test:
    needs: [Lint-Rules, Format-Check]
    runs-on: ubuntu-latest
    steps:
    - name: chekout repository
      uses: actions/checkout@v2
    - name: yarn install
      run: yarn install
    - name: E2E Test Being Done
      run: yarn test:e2e
      